### ISSUE TITLE
Celsius Request

### ISSUE THREAD

**Issue by jsonnos24** [jsh9091/night-shift#1]
Hey, this is the best watch face I’ve seen yet. I was wondering if it’s possible to change the temperature to Celsius? 

I can’t seem to figure out how to change it, and am wondering if it’s hard coded for Fahrenheit?

thanks! 🇨🇦

**Comment by jsh9091** [comment]
Thanks for the positive feedback! Unfortunately Night Shift does not currently support Celsius. It was originally intended to support Celsius with the standard Fitbit user settings, however I encountered trouble getting it to work properly. This was largely due difficulty with testing and debugging because of lack of proper support of the Fitbit brand by Google. I will take another look at the issue when I have time, and see if I can get toggling between Fahrenheit and Celsius to work, and if I can I’ll push an update.

**Comment by adpull** [comment]
I agree that this is definitely the best watch face. Celsius weather would make this my default watch face. 🇨🇦

**Comment by jsh9091** [comment]
Support for Celsius temperature display is now officially available for Night Shift. It will be necessary to update the watch-face to get access to this new feature. To turn on Celsius:  In Fitbit phone app, on "Today" screen, click on profile picture -> Fitbit settings -> Date, Time & units -> UNITS OF MEASUREMENT. An option to switch between Celsius and Fahrenheit is available across from Temperature. However, it may be necessary to toggle the Length value between "Feet, Miles" and "Centimeters, Kilometers" to actually toggle between Fahrenheit and Celsius in the Night Shift watch face. This seems to be an issue with the Fitbit software. If trouble toggling between Celsius and Fahrenheit persists, try uninstalling the watch-face and reinstalling it.

**Comment by jsonnos24** [comment]
You’re amazing!! Thank you so much!  😃On Dec 13, 2024, at 10:34 AM, Joshua Horvath ***@***.***> wrote:﻿
Support for Celsius temperature display is now officially available for Night Shift. It will be necessary to update the watch-face to get access to this new feature. To turn on Celsius:  In Fitbit phone app, on "Today" screen, click on profile picture -> Fitbit settings -> Date, Time & units -> UNITS OF MEASUREMENT. An option to switch between Celsius and Fahrenheit is available across from Temperature. However, it may be necessary to toggle the Length value between "Feet, Miles" and "Centimeters, Kilometers" to actually toggle between Fahrenheit and Celsius in the Night Shift watch face. This seems to be an issue with the Fitbit software. If trouble toggling between Celsius and Fahrenheit persists, try uninstalling the watch-face and reinstalling it.

**Comment by adpull** [comment]
I agree. Thank you so much for the update, this is a brilliant watch face.
